models/Rat.py
from .db import db


class Rat(db.Model):
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    training_data = db.Column(db.String(100), unique=True, nullable=False)
    coordinates = db.Column(db.String(1000), nullable=False)
    match_percentile = db.Column(db.Float(), nullable=False)

models/__init__.py
from flask_sqlalchemy import SQLAlchemy
from .Rat import Rat
from .db  import db 

# db = SQLAlchemy() # ORM converts code written to desired db query. eg- sqllite, mysql etc

__all__ = [
    "db",
    "Rat",
    ]

models/db.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy() # ORM converts code written to desired db query. eg- sqllite, mysql etc

app.py
from routes import *
from routes.main import main
from models import *
import os


def create_app():
    basedir = os.path.abspath(os.path.dirname(__file__))
    app = Flask(__name__ , template_folder='templates')
     
    app.config.from_pyfile('config.cfg')
    Bootstrap(app)
    
    app.config['SQLALCHEMY_DATABASE_URI'] =\
        'sqlite:///' + os.path.join(basedir+'\databases', 'database.db')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)


    app.register_blueprint(main)
    return app

def db_init():
    app = create_app()
    db.init_app(app)
    app.test_request_context().push()
    db.create_all()

    db.session.commit()


if __name__ == '__main__':

    args  =  sys.argv
    
    if len(args) == 1: 
        print("Error: Plese provide one of positional arguments (run or db)")
        sys.exit()      
    elif args[1]== "run":
        app = create_app()
        
        # db_init()
        app.run(debug=True)
    elif args[1]=="db":
        db_init()

routes/__init__.py
from flask_bootstrap import Bootstrap
from flask import Flask, config
import sys


__all__ = [
    "Bootstrap",
    "Flask",
    "config",
    "sys"
]

routes/main.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')


@main.route('/rat_page')
def rat_page():
    return render_template('rat_page.html')

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>
<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">                        
                            <a href="{{ url_for('main.rat_page') }}" class="navbar-item">
                               RAT RAT
                            </a>
                    
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Rat page</h1>
{% endblock %}

templates/rat_page.html
<!DOCTYPE html>
<html>
 
<body>
    <div>
        <h1>GeeksforGeeks</h1>
        <h3>Click on the button to see image</h3>
 
        <!-- img element without src attribute -->
        <img id="image" src="" />
    </div>
 
    <button type="button"
        onclick="show()" id="btnID">
        Show Image
    </button>
 
    <script>
        function show() {
 
            /* Get image and change value
            of src attribute */
            let image = document.getElementById("image");
 
            image.src =
"https://media.geeksforgeeks.org/wp-content/uploads/20210915115837/gfg3.png"
 
            document.getElementById("btnID")
                    .style.display = "none";
        }
    </script>
</body>
 
</html>